version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: kaizntreefe
    ports:
      - 3000:80
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - fe-be
    depends_on:
      - backend
    command: nginx -g 'daemon off;'
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    networks:
      - db-be
    expose:
      - 3306

  backend:
    build:
      context: backend
      target: development
    container_name: kaizntreebe
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - fe-be
      - db-be
    depends_on:
      - db

networks:
  fe-be:
  db-be:
